# This service provides a load-balancing proxy over the facemeplz-app pods.
# By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: facemeplz
spec:
  type: LoadBalancer
  selector:
    app: facemeplz
  ports:
  - port: 80
    targetPort: 80
